openapi: 3.0.0
info:
  title: 03_ReturnBook
  version: 1.0.0
paths:
  /return:
    post:
      summary: 03_ReturnBook
      description: この関数は図書の返却処理を行います。図書番号をbookIdとして入力し、関数を実行してください。成功した場合はUserに返却完了であることを回答してください。足りない引数がある場合は、Userに追加の情報を要求してください。
      operationId: return
      parameters:
        - name: bookId
          in: path
          description: 図書番号
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 返却処理成功
          content:
            application/json:
              schema:
                type: object
                properties:
                  body:
                    type: string
